<a href="https://colab.research.google.com/github/sunwoo0506/sunwoo0506/blob/main/%EC%82%AC%EC%9D%B4%ED%82%B7%EB%9F%B0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [118]:
import pandas as pd
import numpy as np

data = pd.read_csv("final_modudak.csv")
data

메뉴     가격  호수     칼로리  할인율      할인가  원산지 살찔까요      고민
0  [인기]아이펠치킨  16000  11  1200.0  0.5   8000.0  국내산   No  무조건 먹자
1        닭강정  15000  12  1500.0  0.2  12000.0  브라질  Yes    먹지말자
2       간장치킨  14000   9  1600.0  0.2  11200.0  국내산  Yes    먹지말자
3       마늘치킨  14000   9  1800.0  0.2  11200.0  국내산  Yes    먹지말자
4         파닭  14000  11  1300.0  0.2  11200.0  브라질  Yes    먹지말자
5     승일양념치킨  13000  10  1400.0  0.2  10400.0  국내산  Yes    먹지말자
6  양념반 후라이드반  13000  10  1300.0  0.2  10400.0  국내산  Yes    먹지말자
7     황금후라이드  12000  10  1000.0  0.2   9600.0  국내산   No  무조건 먹자
8  [베스트]풀잎치킨   9900  10  1000.0  NaN      NaN  국내산   No  무조건 먹자

In [119]:
data.loc[2,'원산지'] = '미국'

In [120]:
df = data[['가격','호수','칼로리','원산지','살찔까요']].copy()
df

가격  호수     칼로리  원산지 살찔까요
0  16000  11  1200.0  국내산   No
1  15000  12  1500.0  브라질  Yes
2  14000   9  1600.0   미국  Yes
3  14000   9  1800.0  국내산  Yes
4  14000  11  1300.0  브라질  Yes
5  13000  10  1400.0  국내산  Yes
6  13000  10  1300.0  국내산  Yes
7  12000  10  1000.0  국내산   No
8   9900  10  1000.0  국내산   No

In [121]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9 entries, 0 to 8
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   가격      9 non-null      int64  
 1   호수      9 non-null      int64  
 2   칼로리     9 non-null      float64
 3   원산지     9 non-null      object 
 4   살찔까요    9 non-null      object 
dtypes: float64(1), int64(2), object(2)
memory usage: 488.0+ bytes


In [122]:
#label 인코딩
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

le.fit(df['원산지'])
le.transform(df['원산지'])



array([0, 2, 1, 0, 2, 0, 0, 0, 0])

In [123]:
le.fit_transform(df['원산지'])


array([0, 2, 1, 0, 2, 0, 0, 0, 0])

In [124]:
df['원산지'] =le.fit_transform(df['원산지'])
df

가격  호수     칼로리  원산지 살찔까요
0  16000  11  1200.0    0   No
1  15000  12  1500.0    2  Yes
2  14000   9  1600.0    1  Yes
3  14000   9  1800.0    0  Yes
4  14000  11  1300.0    2  Yes
5  13000  10  1400.0    0  Yes
6  13000  10  1300.0    0  Yes
7  12000  10  1000.0    0   No
8   9900  10  1000.0    0   No

In [125]:
df['살찔까요']  = le.fit_transform(df['살찔까요'])
df

가격  호수     칼로리  원산지  살찔까요
0  16000  11  1200.0    0     0
1  15000  12  1500.0    2     1
2  14000   9  1600.0    1     1
3  14000   9  1800.0    0     1
4  14000  11  1300.0    2     1
5  13000  10  1400.0    0     1
6  13000  10  1300.0    0     1
7  12000  10  1000.0    0     0
8   9900  10  1000.0    0     0

In [126]:
# 한번에 여러개 컬럼 인코딩

df = data[['가격','호수','칼로리','원산지','살찔까요']].copy()
df

가격  호수     칼로리  원산지 살찔까요
0  16000  11  1200.0  국내산   No
1  15000  12  1500.0  브라질  Yes
2  14000   9  1600.0   미국  Yes
3  14000   9  1800.0  국내산  Yes
4  14000  11  1300.0  브라질  Yes
5  13000  10  1400.0  국내산  Yes
6  13000  10  1300.0  국내산  Yes
7  12000  10  1000.0  국내산   No
8   9900  10  1000.0  국내산   No

In [127]:
# 한번에 레이블 인코딩 1
cols = ['원산지','살찔까요']

from sklearn.preprocessing import LabelEncoder

for col in cols:
  le = LabelEncoder()
  df[col]  = le.fit_transform(df[col])

df

가격  호수     칼로리  원산지  살찔까요
0  16000  11  1200.0    0     0
1  15000  12  1500.0    2     1
2  14000   9  1600.0    1     1
3  14000   9  1800.0    0     1
4  14000  11  1300.0    2     1
5  13000  10  1400.0    0     1
6  13000  10  1300.0    0     1
7  12000  10  1000.0    0     0
8   9900  10  1000.0    0     0

In [128]:
# 한번에 레이블 인코딩 2

df = data[['가격','호수','칼로리','원산지','살찔까요']].copy()
df

df.info()


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9 entries, 0 to 8
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   가격      9 non-null      int64  
 1   호수      9 non-null      int64  
 2   칼로리     9 non-null      float64
 3   원산지     9 non-null      object 
 4   살찔까요    9 non-null      object 
dtypes: float64(1), int64(2), object(2)
memory usage: 488.0+ bytes


In [129]:
df.select_dtypes(include='object').columns

Index(['원산지', '살찔까요'], dtype='object')

In [130]:
cols = df.select_dtypes(include='object').columns
from sklearn.preprocessing import LabelEncoder

for col in cols:
  le = LabelEncoder()
  df[col]  = le.fit_transform(df[col])
df

가격  호수     칼로리  원산지  살찔까요
0  16000  11  1200.0    0     0
1  15000  12  1500.0    2     1
2  14000   9  1600.0    1     1
3  14000   9  1800.0    0     1
4  14000  11  1300.0    2     1
5  13000  10  1400.0    0     1
6  13000  10  1300.0    0     1
7  12000  10  1000.0    0     0
8   9900  10  1000.0    0     0

In [131]:
#원핫인코딩

df = data[['가격','호수','칼로리','원산지','살찔까요']].copy()
df

from sklearn.preprocessing import OneHotEncoder

ohe=OneHotEncoder(sparse=False) #기본 옵션sparse 을 False로 지정해줘 우리가 array 형태로 반환 받을 수 있음
cat = ohe.fit_transform(df[['원산지']])

cat



/usr/local/lib/python3.10/dist-packages/sklearn/preprocessing/_encoders.py:868: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(


array([[1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.]])

In [132]:
ohe.categories_


[array(['국내산', '미국', '브라질'], dtype=object)]

In [133]:
ohe.get_feature_names_out()

array(['원산지_국내산', '원산지_미국', '원산지_브라질'], dtype=object)

In [134]:
df_cat = pd.DataFrame(cat,columns=ohe.get_feature_names_out())

In [135]:
df= pd.concat([df,df_cat], axis=1)

In [136]:
df=df.drop('원산지', axis=1)
df

가격  호수     칼로리 살찔까요  원산지_국내산  원산지_미국  원산지_브라질
0  16000  11  1200.0   No      1.0     0.0      0.0
1  15000  12  1500.0  Yes      0.0     0.0      1.0
2  14000   9  1600.0  Yes      0.0     1.0      0.0
3  14000   9  1800.0  Yes      1.0     0.0      0.0
4  14000  11  1300.0  Yes      0.0     0.0      1.0
5  13000  10  1400.0  Yes      1.0     0.0      0.0
6  13000  10  1300.0  Yes      1.0     0.0      0.0
7  12000  10  1000.0   No      1.0     0.0      0.0
8   9900  10  1000.0   No      1.0     0.0      0.0

In [111]:
# **[여러 개 컬럼 한 번에 인코딩]**



df = data[['가격','호수','칼로리','원산지','살찔까요']].copy()
df

가격  호수     칼로리  원산지 살찔까요
0  16000  11  1200.0  국내산   No
1  15000  12  1500.0  브라질  Yes
2  14000   9  1600.0   미국  Yes
3  14000   9  1800.0  국내산  Yes
4  14000  11  1300.0  브라질  Yes
5  13000  10  1400.0  국내산  Yes
6  13000  10  1300.0  국내산  Yes
7  12000  10  1000.0  국내산   No
8   9900  10  1000.0  국내산   No

In [154]:
# 1) 리스트형태로 넣기
df = data[['가격','호수','칼로리','원산지','살찔까요']].copy()
df

from sklearn.preprocessing import OneHotEncoder

ohe=OneHotEncoder(sparse=False)

cat = ohe.fit_transform(df[['원산지','살찔까요']])
cat

df_cat = pd.DataFrame(cat, columns = ohe.get_feature_names_out())

df_cat

df = pd.concat([df,df_cat], axis=1)
df

df = df.drop(['원산지','살찔까요'], axis=1)
df

/usr/local/lib/python3.10/dist-packages/sklearn/preprocessing/_encoders.py:868: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(


가격  호수     칼로리  원산지_국내산  원산지_미국  원산지_브라질  살찔까요_No  살찔까요_Yes
0  16000  11  1200.0      1.0     0.0      0.0      1.0       0.0
1  15000  12  1500.0      0.0     0.0      1.0      0.0       1.0
2  14000   9  1600.0      0.0     1.0      0.0      0.0       1.0
3  14000   9  1800.0      1.0     0.0      0.0      0.0       1.0
4  14000  11  1300.0      0.0     0.0      1.0      0.0       1.0
5  13000  10  1400.0      1.0     0.0      0.0      0.0       1.0
6  13000  10  1300.0      1.0     0.0      0.0      0.0       1.0
7  12000  10  1000.0      1.0     0.0      0.0      1.0       0.0
8   9900  10  1000.0      1.0     0.0      0.0      1.0       0.0

In [156]:
# 2) select_dtypes 사용

df = data[['가격','호수','칼로리','원산지','살찔까요']].copy()
df

from sklearn.preprocessing import OneHotEncoder

ohe=OneHotEncoder(sparse=False)
cols = df.select_dtypes(include='object').columns
cat = ohe.fit_transform(df[cols])

df_cat = pd.DataFrame(cat,columns=ohe.get_feature_names_out())
df = pd.concat([df,df_cat], axis=1)
df

df = df.drop(cols, axis=1)
df

/usr/local/lib/python3.10/dist-packages/sklearn/preprocessing/_encoders.py:868: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(


가격  호수     칼로리  원산지_국내산  원산지_미국  원산지_브라질  살찔까요_No  살찔까요_Yes
0  16000  11  1200.0      1.0     0.0      0.0      1.0       0.0
1  15000  12  1500.0      0.0     0.0      1.0      0.0       1.0
2  14000   9  1600.0      0.0     1.0      0.0      0.0       1.0
3  14000   9  1800.0      1.0     0.0      0.0      0.0       1.0
4  14000  11  1300.0      0.0     0.0      1.0      0.0       1.0
5  13000  10  1400.0      1.0     0.0      0.0      0.0       1.0
6  13000  10  1300.0      1.0     0.0      0.0      0.0       1.0
7  12000  10  1000.0      1.0     0.0      0.0      1.0       0.0
8   9900  10  1000.0      1.0     0.0      0.0      1.0       0.0

In [173]:
# 판다스 활용 원핫인코딩

df = data[['가격','호수','칼로리','원산지','살찔까요']].copy()
df

df = pd.get_dummies(df)

In [174]:
df.head()


가격  호수     칼로리  원산지_국내산  원산지_미국  원산지_브라질  살찔까요_No  살찔까요_Yes
0  16000  11  1200.0        1       0        0        1         0
1  15000  12  1500.0        0       0        1        0         1
2  14000   9  1600.0        0       1        0        0         1
3  14000   9  1800.0        1       0        0        0         1
4  14000  11  1300.0        0       0        1        0         1

In [175]:
from sklearn.preprocessing import StandardScaler

scaler=StandardScaler()
scaler.fit_transform(df[['가격']])

array([[ 1.54246993],
       [ 0.94150762],
       [ 0.34054531],
       [ 0.34054531],
       [ 0.34054531],
       [-0.260417  ],
       [-0.260417  ],
       [-0.86137931],
       [-2.12340016]])

In [176]:
cols=['가격','호수','칼로리']
df[cols] = scaler.fit_transform(df[cols])
df

가격        호수       칼로리  원산지_국내산  원산지_미국  원산지_브라질  살찔까요_No  살찔까요_Yes
0  1.542470  0.848875 -0.577920        1       0        0        1         0
1  0.941508  1.940285  0.622376        0       0        1        0         1
2  0.340545 -1.333946  1.022475        0       1        0        0         1
3  0.340545 -1.333946  1.822672        1       0        0        0         1
4  0.340545  0.848875 -0.177822        0       0        1        0         1
5 -0.260417 -0.242536  0.222277        1       0        0        0         1
6 -0.260417 -0.242536 -0.177822        1       0        0        0         1
7 -0.861379 -0.242536 -1.378118        1       0        0        1         0
8 -2.123400 -0.242536 -1.378118        1       0        0        1         0

In [177]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()

cols=['가격','호수','칼로리']
df[cols] = scaler.fit_transform(df[cols])
df

가격        호수    칼로리  원산지_국내산  원산지_미국  원산지_브라질  살찔까요_No  살찔까요_Yes
0  1.000000  0.666667  0.250        1       0        0        1         0
1  0.836066  1.000000  0.625        0       0        1        0         1
2  0.672131  0.000000  0.750        0       1        0        0         1
3  0.672131  0.000000  1.000        1       0        0        0         1
4  0.672131  0.666667  0.375        0       0        1        0         1
5  0.508197  0.333333  0.500        1       0        0        0         1
6  0.508197  0.333333  0.375        1       0        0        0         1
7  0.344262  0.333333  0.000        1       0        0        1         0
8  0.000000  0.333333  0.000        1       0        0        1         0

In [178]:
# 4. 사이킷런에서 제공하는 데이터셋
# 유방암 데이터

from sklearn.datasets import load_breast_cancer
dataset = load_breast_cancer()
dataset


{'data': array([[1.799e+01, 1.038e+01, 1.228e+02, ..., 2.654e-01, 4.601e-01,
         1.189e-01],
        [2.057e+01, 1.777e+01, 1.329e+02, ..., 1.860e-01, 2.750e-01,
         8.902e-02],
        [1.969e+01, 2.125e+01, 1.300e+02, ..., 2.430e-01, 3.613e-01,
         8.758e-02],
        ...,
        [1.660e+01, 2.808e+01, 1.083e+02, ..., 1.418e-01, 2.218e-01,
         7.820e-02],
        [2.060e+01, 2.933e+01, 1.401e+02, ..., 2.650e-01, 4.087e-01,
         1.240e-01],
        [7.760e+00, 2.454e+01, 4.792e+01, ..., 0.000e+00, 2.871e-01,
         7.039e-02]]),
 'target': array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
        0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0,
        1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0,
        1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
        1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0

In [179]:
dataset.feature_names

array(['mean radius', 'mean texture', 'mean perimeter', 'mean area',
       'mean smoothness', 'mean compactness', 'mean concavity',
       'mean concave points', 'mean symmetry', 'mean fractal dimension',
       'radius error', 'texture error', 'perimeter error', 'area error',
       'smoothness error', 'compactness error', 'concavity error',
       'concave points error', 'symmetry error',
       'fractal dimension error', 'worst radius', 'worst texture',
       'worst perimeter', 'worst area', 'worst smoothness',
       'worst compactness', 'worst concavity', 'worst concave points',
       'worst symmetry', 'worst fractal dimension'], dtype='<U23')

In [180]:
dataset.target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0,
       1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0,
       1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0,
       0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1,
       1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0,

In [182]:
dataset.data[:2]

array([[1.799e+01, 1.038e+01, 1.228e+02, 1.001e+03, 1.184e-01, 2.776e-01,
        3.001e-01, 1.471e-01, 2.419e-01, 7.871e-02, 1.095e+00, 9.053e-01,
        8.589e+00, 1.534e+02, 6.399e-03, 4.904e-02, 5.373e-02, 1.587e-02,
        3.003e-02, 6.193e-03, 2.538e+01, 1.733e+01, 1.846e+02, 2.019e+03,
        1.622e-01, 6.656e-01, 7.119e-01, 2.654e-01, 4.601e-01, 1.189e-01],
       [2.057e+01, 1.777e+01, 1.329e+02, 1.326e+03, 8.474e-02, 7.864e-02,
        8.690e-02, 7.017e-02, 1.812e-01, 5.667e-02, 5.435e-01, 7.339e-01,
        3.398e+00, 7.408e+01, 5.225e-03, 1.308e-02, 1.860e-02, 1.340e-02,
        1.389e-02, 3.532e-03, 2.499e+01, 2.341e+01, 1.588e+02, 1.956e+03,
        1.238e-01, 1.866e-01, 2.416e-01, 1.860e-01, 2.750e-01, 8.902e-02]])

In [185]:
cancer_df = pd.DataFrame(data=dataset.data, columns=dataset.feature_names)
cancer_df

mean radius  mean texture  mean perimeter  mean area  mean smoothness  \
0          17.99         10.38          122.80     1001.0          0.11840   
1          20.57         17.77          132.90     1326.0          0.08474   
2          19.69         21.25          130.00     1203.0          0.10960   
3          11.42         20.38           77.58      386.1          0.14250   
4          20.29         14.34          135.10     1297.0          0.10030   
..           ...           ...             ...        ...              ...   
564        21.56         22.39          142.00     1479.0          0.11100   
565        20.13         28.25          131.20     1261.0          0.09780   
566        16.60         28.08          108.30      858.1          0.08455   
567        20.60         29.33          140.10     1265.0          0.11780   
568         7.76         24.54           47.92      181.0          0.05263   

     mean compactness  mean concavity  mean concave points  mean symmetry  \
0             0.27760         0.30010              0.14710         0.2419   
1             0.07864         0.08690              0.07017         0.1812   
2             0.15990         0.19740              0.12790         0.2069   
3             0.28390         0.24140              0.10520         0.2597   
4             0.13280         0.19800              0.10430         0.1809   
..                ...             ...                  ...            ...   
564           0.11590         0.24390              0.13890         0.1726   
565           0.10340         0.14400              0.09791         0.1752   
566           0.10230         0.09251              0.05302         0.1590   
567           0.27700         0.35140              0.15200         0.2397   
568           0.04362         0.00000              0.00000         0.1587   

     mean fractal dimension  ...  worst radius  worst texture  \
0                   0.07871  ...        25.380          17.33   
1                   0.05667  ...        24.990          23.41   
2                   0.05999  ...        23.570          25.53   
3                   0.09744  ...        14.910          26.50   
4                   0.05883  ...        22.540          16.67   
..                      ...  ...           ...            ...   
564                 0.05623  ...        25.450          26.40   
565                 0.05533  ...        23.690          38.25   
566                 0.05648  ...        18.980          34.12   
567                 0.07016  ...        25.740          39.42   
568                 0.05884  ...         9.456          30.37   

     worst perimeter  worst area  worst smoothness  worst compactness  \
0             184.60      2019.0           0.16220            0.66560   
1             158.80      1956.0           0.12380            0.18660   
2             152.50      1709.0           0.14440            0.42450   
3              98.87       567.7           0.20980            0.86630   
4             152.20      1575.0           0.13740            0.20500   
..               ...         ...               ...                ...   
564           166.10      2027.0           0.14100            0.21130   
565           155.00      1731.0           0.11660            0.19220   
566           126.70      1124.0           0.11390            0.30940   
567           184.60      1821.0           0.16500            0.86810   
568            59.16       268.6           0.08996            0.06444   

     worst concavity  worst concave points  worst symmetry  \
0             0.7119                0.2654          0.4601   
1             0.2416                0.1860          0.2750   
2             0.4504                0.2430          0.3613   
3             0.6869                0.2575          0.6638   
4             0.4000                0.1625          0.2364   
..               ...                   ...             ...   
564           0.4107                0.2216         

In [187]:
cancer_df['target'] = dataset.target
cancer_df.head()

mean radius  mean texture  mean perimeter  mean area  mean smoothness  \
0        17.99         10.38          122.80     1001.0          0.11840   
1        20.57         17.77          132.90     1326.0          0.08474   
2        19.69         21.25          130.00     1203.0          0.10960   
3        11.42         20.38           77.58      386.1          0.14250   
4        20.29         14.34          135.10     1297.0          0.10030   

   mean compactness  mean concavity  mean concave points  mean symmetry  \
0           0.27760          0.3001              0.14710         0.2419   
1           0.07864          0.0869              0.07017         0.1812   
2           0.15990          0.1974              0.12790         0.2069   
3           0.28390          0.2414              0.10520         0.2597   
4           0.13280          0.1980              0.10430         0.1809   

   mean fractal dimension  ...  worst texture  worst perimeter  worst area  \
0                 0.07871  ...          17.33           184.60      2019.0   
1                 0.05667  ...          23.41           158.80      1956.0   
2                 0.05999  ...          25.53           152.50      1709.0   
3                 0.09744  ...          26.50            98.87       567.7   
4                 0.05883  ...          16.67           152.20      1575.0   

   worst smoothness  worst compactness  worst concavity  worst concave points  \
0            0.1622             0.6656           0.7119                0.2654   
1            0.1238             0.1866           0.2416                0.1860   
2            0.1444             0.4245           0.4504                0.2430   
3            0.2098             0.8663           0.6869                0.2575   
4            0.1374             0.2050           0.4000                0.1625   

   worst symmetry  worst fractal dimension  target  
0          0.4601                  0.11890       0  
1          0.2750                  0.08902       0  
2          0.3613                  0.08758       0  
3          0.6638                  0.17300       0  
4          0.2364                  0.07678       0  

[5 rows x 31 columns]

In [197]:
# 당뇨병데이터 불러오기
from sklearn.datasets import load_diabetes

dataset = load_diabetes()
dataset

dataset.feature_names
dataset.target
dataset.data[:2]

diabetes_df=pd.DataFrame(data=dataset.data, columns=dataset.feature_names)
diabetes_df

diabetes_df['target']=dataset.target
diabetes_df.head()


age       sex       bmi        bp        s1        s2        s3  \
0  0.038076  0.050680  0.061696  0.021872 -0.044223 -0.034821 -0.043401   
1 -0.001882 -0.044642 -0.051474 -0.026328 -0.008449 -0.019163  0.074412   
2  0.085299  0.050680  0.044451 -0.005670 -0.045599 -0.034194 -0.032356   
3 -0.089063 -0.044642 -0.011595 -0.036656  0.012191  0.024991 -0.036038   
4  0.005383 -0.044642 -0.036385  0.021872  0.003935  0.015596  0.008142   

         s4        s5        s6  target  
0 -0.002592  0.019907 -0.017646   151.0  
1 -0.039493 -0.068332 -0.092204    75.0  
2 -0.002592  0.002861 -0.025930   141.0  
3  0.034309  0.022688 -0.009362   206.0  
4 -0.002592 -0.031988 -0.046641   135.0

In [202]:
cancer_df.head()

mean radius  mean texture  mean perimeter  mean area  mean smoothness  \
0        17.99         10.38          122.80     1001.0          0.11840   
1        20.57         17.77          132.90     1326.0          0.08474   
2        19.69         21.25          130.00     1203.0          0.10960   
3        11.42         20.38           77.58      386.1          0.14250   
4        20.29         14.34          135.10     1297.0          0.10030   

   mean compactness  mean concavity  mean concave points  mean symmetry  \
0           0.27760          0.3001              0.14710         0.2419   
1           0.07864          0.0869              0.07017         0.1812   
2           0.15990          0.1974              0.12790         0.2069   
3           0.28390          0.2414              0.10520         0.2597   
4           0.13280          0.1980              0.10430         0.1809   

   mean fractal dimension  ...  worst texture  worst perimeter  worst area  \
0                 0.07871  ...          17.33           184.60      2019.0   
1                 0.05667  ...          23.41           158.80      1956.0   
2                 0.05999  ...          25.53           152.50      1709.0   
3                 0.09744  ...          26.50            98.87       567.7   
4                 0.05883  ...          16.67           152.20      1575.0   

   worst smoothness  worst compactness  worst concavity  worst concave points  \
0            0.1622             0.6656           0.7119                0.2654   
1            0.1238             0.1866           0.2416                0.1860   
2            0.1444             0.4245           0.4504                0.2430   
3            0.2098             0.8663           0.6869                0.2575   
4            0.1374             0.2050           0.4000                0.1625   

   worst symmetry  worst fractal dimension  target  
0          0.4601                  0.11890       0  
1          0.2750                  0.08902       0  
2          0.3613                  0.08758       0  
3          0.6638                  0.17300       0  
4          0.2364                  0.07678       0  

[5 rows x 31 columns]

In [205]:
# 머신러닝 : 분류

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    cancer_df.drop('target', axis=1), cancer_df['target'], test_size=0.3, random_state=1004)

X_train.head()

mean radius  mean texture  mean perimeter  mean area  mean smoothness  \
350       11.660         17.07           73.70      421.0          0.07561   
384       13.280         13.72           85.79      541.8          0.08363   
7         13.710         20.83           90.20      577.9          0.11890   
557        9.423         27.88           59.26      271.3          0.08123   
49        13.490         22.30           86.91      561.0          0.08752   

     mean compactness  mean concavity  mean concave points  mean symmetry  \
350           0.03630        0.008306              0.01162         0.1671   
384           0.08575        0.050770              0.02864         0.1617   
7             0.16450        0.093660              0.05985         0.2196   
557           0.04971        0.000000              0.00000         0.1742   
49            0.07698        0.047510              0.03384         0.1809   

     mean fractal dimension  ...  worst radius  worst texture  \
350                 0.05731  ...         13.28          19.74   
384                 0.05594  ...         14.24          17.37   
7                   0.07451  ...         17.06          28.14   
557                 0.06059  ...         10.49          34.24   
49                  0.05718  ...         15.15          31.82   

     worst perimeter  worst area  worst smoothness  worst compactness  \
350            83.61       542.5           0.09958            0.06476   
384            96.59       623.7           0.11660            0.26850   
7             110.60       897.0           0.16540            0.36820   
557            66.50       330.6           0.10730            0.07158   
49             99.00       698.8           0.11620            0.17110   

     worst concavity  worst concave points  worst symmetry  \
350          0.03046               0.04262          0.2731   
384          0.28660               0.09173          0.2736   
7            0.26780               0.15560          0.3196   
557          0.00000               0.00000          0.2475   
49           0.22820               0.12820          0.2871   

     worst fractal dimension  
350                  0.06825  
384                  0.07320  
7                    0.11510  
557                  0.06969  
49                   0.06917  

[5 rows x 30 columns]

In [206]:
y_train.head()

350    1
384    1
7      0
557    1
49     1
Name: target, dtype: int64

In [207]:
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((398, 30), (171, 30), (398,), (171,))

In [210]:
# 의사결정나무(DecisionTree)

from sklearn.tree import DecisionTreeClassifier

model = DecisionTreeClassifier()
model.fit(X_train,y_train)
pred = model.predict(X_test)
pred

array([1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0,
       1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0,
       1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1,
       1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1,
       1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1,
       1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1,
       1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0])

In [211]:
#정확도 accuracy_score(실제값,예측값)

from sklearn.metrics import accuracy_score
accuracy_score(y_test,pred)

0.8947368421052632

In [212]:
#머신러닝: 회귀

#검증데이터 분리

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(diabetes_df.drop('target',axis=1), diabetes_df['target'], test_size=0.3, random_state=1004)

X_train.head()

age       sex       bmi        bp        s1        s2        s3  \
232  0.012648  0.050680  0.000261 -0.011420  0.039710  0.057245 -0.039719   
81   0.012648  0.050680 -0.022373 -0.029770  0.010815  0.028435 -0.021311   
227  0.067136  0.050680 -0.029918  0.057437 -0.000193 -0.015719  0.074412   
334 -0.060003  0.050680 -0.047163 -0.022885 -0.071743 -0.057681 -0.006584   
83  -0.038207 -0.044642  0.009961 -0.046985 -0.059359 -0.052983 -0.010266   

           s4        s5        s6  
232  0.056081  0.024055  0.032059  
81   0.034309 -0.006081 -0.001078  
227 -0.050564 -0.038460  0.007207  
334 -0.039493 -0.062917 -0.054925  
83  -0.039493 -0.015999 -0.042499

In [213]:
y_train.head()


232    259.0
81      51.0
227    108.0
334     72.0
83     210.0
Name: target, dtype: float64

In [214]:
# 데이터의 크기

X_train.shape, X_test.shape, y_train.shape, y_test.shape



((309, 10), (133, 10), (309,), (133,))

In [216]:
# 모델 선택

from sklearn.linear_model import LinearRegression

model = LinearRegression()

model.fit(X_train,y_train)

pred= model.predict(X_test)
pred

array([128.42468606, 135.08774266, 154.78504343, 106.09306564,
       149.54478558, 165.32708009, 140.29166154, 167.9600165 ,
        69.44851384, 189.42811434, 144.98692247, 150.10700196,
       211.15983244, 108.59257071, 160.3856331 , 154.09855476,
       198.78116874, 101.16062264, 165.82852734, 196.03659567,
       147.16472505, 108.25668788, 207.27889551, 127.53191954,
       181.85997027, 228.49975565,  86.59589481, 155.35081963,
       182.49593133, 182.96390209, 207.63119699, 199.81134435,
       157.35809543,  61.82465786,  88.11634158,  95.75033061,
       134.03120864,  85.95903914, 177.69650387, 249.40014721,
       171.77206628, 204.71572412, 239.12149428,  89.24927278,
       244.20385113, 180.36498587, 161.10608699, 119.14846149,
       102.81815844, 153.35400825, 129.06743815, 208.80206598,
       107.93927973, 138.81355171, 166.04217088,  86.04455248,
       181.03094575, 117.97907348,  79.04947426, 127.20387612,
       194.05986421, 205.13463546, 233.84790901,  48.53

In [217]:
#평가(MSE, mean_squared_error(실제값,예측))

from sklearn.metrics import mean_squared_error
mean_squared_error(y_test,pred)



3229.454787929743